### ISSUE TITLE
List all scenarios/tests

### ISSUE THREAD

**Issue by patricia-ternes** [patricia-ternes/COMP5991M-2023-project#1]
Before jump to development, think about all possible scenarios and what the code should do.

**Comment by RFurze** [comment]
- [x] Function name: get_range():
- [x] Input: two lists of float/int, representing either side of the range
- [x] Return: Pair of float numbers
- [x] Test: No overlap - return "No overlap"
- [x] Test: Input has at least 2 rows - return "Minimum 2 inputs needed"
- [x] Test: Input type: (float/int float/int) - return "Input float/int data only"
- [x] Test: Input format: (float/int float/int) - return "Input lists only"
- [x] Test: Input lists are the same length - return "Input lists are not the same length"
